#pragma once
#include "../hooking/types.hpp"
#include <string>

namespace Cheat
{
	namespace Features
	{
		extern int JumpVectorPosition;
		extern int SpeedometerVectorPosition;
		extern int ImpactAmmoVectorPosition;
		extern int CustomAmmoVectorPosition;
		extern int ParticleAmmoVectorPosition;
		extern int FontTypeVectorPosition;
		extern int AnimationsVectorPosition;
		extern int ScenariosVectorPosition;
		extern int PedMovementVectorPosition;
		extern int OpenVehicleDoorPosition;
		extern int CloseVehicleDoorPosition;
		extern int FastSuperRunPosition;
		extern int TriggerbotVectorPosition;
		extern int SelfInvisiblityVectorPosition;
		extern int SelectedPlayer;
		extern int PlayerOpacityInt;
		extern bool BlockAllScriptEvents;
		extern bool ProtectionBlockReports;
		extern bool ProtectionScriptEvents_SMS;
		extern bool ProtectionScriptEvents_TSEStart;
		extern bool ProtectionScriptEvents_Notification;
		extern bool ProtectionScriptEvents_InteriorControl;
		extern bool ProtectionScriptEvents_TransactionError;
		extern bool ProtectionScriptEvents_Kicks;
		extern bool ProtectionScriptEvents_InteriorKick;
		extern bool ProtectionScriptEvents_CEORaid;
		extern bool ProtectionScriptEvents_VehicleKick;
		extern bool ProtectionScriptEvents_StartActivity;
		extern bool ProtectionScriptEvents_CEOMoney;
		extern bool ProtectionScriptEvents_CEOBan;
		extern bool ProtectionScriptEvents_CEOKick;
		extern bool ProtectionScriptEvents_GiveCollectible;
		extern bool ProtectionScriptEvents_WarehouseTeleport;
		extern bool ProtectionScriptEvents_PropertyTeleport;
		extern bool ProtectionScriptEvents_CayoPericoTeleport;
		extern bool ProtectionScriptEvents_ForceIntoMission;
		extern bool ProtectionScriptEvents_Bounty;
		extern bool ProtectionScriptEvents_ClearWantedlevel;
		extern bool ProtectionScriptEvents_GameBanner;
		extern bool ProtectionScriptEvents_Crash;
		extern bool ProtectionScriptEvents_PersonalVehicleDestroyed;
		extern bool ProtectionScriptEvents_RemoteOffradar;
		extern bool ProtectionScriptEvents_SendToCutscene;
		extern bool ProtectionScriptEvents_SendToLocation;
		extern bool ProtectionScriptEvents_SoundSpam;
		extern bool ProtectionScriptEvents_Spectate;
		extern bool DisableTransactionErrorWarning;
		extern bool DisableCutscenes;
		extern bool HideVehiclePreview;
		extern bool ShowJoiningPlayersNotification;
		extern bool VehicleSpawnerSpawnInsideVehicle;
		extern bool VehicleSpawnerDeleteOldVehicle;
		extern bool VehicleSpawnerSpawnWithGodmode;
		extern bool VehicleSpawnerSpawnMaxUpgraded;
		extern bool VehicleSpawnerSpawnAirVehicleAir;
		extern bool MoneyLoopNC;
		extern int VehicleSpawnerLicensePlateVectorPosition;
		extern std::string VehicleSpawnerCustomLicensePlateTextString;
		extern bool HidePlayerInformationBox;
		extern bool HideSelectableInformationBox;
		extern bool ControllableAnimations;
		extern bool AllPlayersExclusionsSelf;
		extern bool AllPlayersExclusionsFriends;
		extern bool AllPlayersExclusionsHost;
		extern bool TeleportTransition;
		extern bool NoTextureFileOverwrite;
		extern bool SafeMode;
		extern bool StickyBombLimit;
		extern bool WorldBlackout;
		extern bool NoGravity;
		extern bool WorldSnow;
		extern bool SpectatePlayer;
		extern bool SlowMotion;
		extern bool MobileRadio;
		extern bool HideMinimap;
		extern bool Spin;
		extern bool Seatbelt;

		void Loop();
		extern bool GodmodeBool;
		extern bool GodmodeWasEnabled;
		void Godmode(bool toggle);
		extern bool NeverWantedBool;
		void NeverWanted();
		extern bool NoWeaponReloadBool;
		void NoWeaponReload();
		extern bool InfiniteAmmoBool;
		extern bool InfiniteAmmoWasEnabled;
		void InfiniteAmmo(bool toggle);
		extern float GravityGunEntityDistance;
		extern bool GravityGunBool;
		void GravityGun();
		extern bool DisableHUDBool;
		void DisableHUD();
		extern bool AutoTeleportToWaypointBool;
		void AutoTeleportToWaypoint();
		extern bool OneHitKillBool;
		extern bool OneHitKillWasEnabled;
		void OneHitKill();
		extern bool PauseTimeBool;
		void PauseTime(bool toggle);
		extern bool ExplosiveMeleeBool;
		void ExplosiveMelee();
		extern bool OrbitalCannonCooldownBypassBool;
		void OrbitalCannonCooldownBypass();
		extern bool ShowFPSBool;
		void ShowFPS();
		extern bool JumpAroundModeBool;
		void JumpAroundMode();
		extern bool VehicleHornBoostBool;
		void VehicleHornBoost();
		extern bool VehicleGodmodeBool;
		void VehicleGodmode(bool toggle);
		extern bool VehicleInvisibleBool;
		void VehicleInvisible(bool toggle);
		extern bool FreezeStationBool;
		extern bool FreezeStationWasEnabled;
		void FreezeStation();
		extern bool WeaponRapidFireBool;
		void WeaponRapidFire();
		extern bool NoClipBool;
		void NoClip();
		extern bool RainbowVehicleBool;
		void RainbowVehicle();
		extern bool DeleteGunBool;
		void DeleteGun();
		extern bool NerfBulletsBool;
		extern bool NerfBulletsWasEnabled;
		void NerfBullets();
		extern bool EntityInformationGunBool;
		void EntityInformationGun();
		extern bool NoRagdollAndSeatbeltBool;
		void NoRagdollAndSeatbelt(bool toggle);
		extern bool FreezeSelectedPlayerBool;
		void FreezeSelectedPlayer();
		extern bool FreezeAllPlayersBool;
		void FreezeAllPlayers();
		extern bool SuperBrakesBool;
		void SuperBrakes();
		extern bool TinyPlayerBool;
		void TinyPlayer(bool toggle);
		extern bool UnlimitedRocketBoostBool;
		void UnlimitedRocketBoost();
		extern bool ShootEntitiesBool;
		extern std::string ShootEntitiesCurrent;
		void ShootEntities();
		extern bool PlayerESPBool;
		void PlayerESP();
		extern bool OffRadarBool;
		void OffRadar();
		extern bool ExplodeLoopSelectedPlayerBool;
		void ExplodeLoopSelectedPlayer();
		extern bool DriveOnWaterBool;
		void DriveOnWater();
		extern bool SuperManBool;
		void SuperMan();
		extern bool ShakeCamSelectedPlayerBool;
		void ShakeCamSelectedPlayer();
		extern bool RainbowGunBool;
		void RainbowGun();
		extern bool DisableMobilePhoneBool;
		void DisableMobilePhone();
		extern bool NoIdleKickBool;
		void NoIdleKick();
		extern bool MoneyLoop;
		void money7();
		extern bool Spin;
		void spin();
		extern bool Seatbelt;
		void seatbelt();
		extern bool CopsTurnBlindEyeBool;
		void CopsTurnBlindEye();
		extern bool VehicleWeaponsBool;
		extern bool VehicleWeapons_TankRounds;
		extern bool VehicleWeapons_VehicleRockets;
		extern bool VehicleWeapons_Fireworks;
		extern bool VehicleWeapons_DrawLaser;
		void VehicleWeapons();
		extern bool AutoGiveAllWeaponsBool;
		void AutoGiveAllWeapons();
		extern bool AutoGiveAllWeaponUpgradesBool;
		void AutoGiveAllWeaponUpgrades();
		extern bool CrossHairBool;
		extern bool CrossHairADSOnlyBool;
		void CrossHair();
		extern bool RGBDiscoBool;
		extern bool RGBDiscoFirstCall;
		void RGBDisco();
		extern bool WeaponInvisibilityBool;
		extern bool WeaponInvisibilityWasEnabled;
		void WeaponInvisibility(bool toggle);
		extern bool SessionLockFriendsOnlyBool;
		void SessionLockFriendsOnly();
		extern bool ShowTVBool;
		extern bool ShowTVWasEnabled;
		void ShowTV(bool toggle);
	}
}